export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_CONTACTS_SUCCESS = 'SET_CONTACTS_SUCCESS';
export const SET_CONTACTS_FAIL = 'SET_CONTACTS_FAIL';
export const SET_ACTIVE_CONTACT = 'SET_ACTIVE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const SET_ONE_CONTACT = 'SET_ONE_CONTACT';
export const SET_ONE_CONTACT_SUCCESS = 'SET_ONE_CONTACT_SUCCESS';
